if(NOT DEFINED ROBORUN_BIN OR NOT DEFINED ROBORUN_PROGRAM OR NOT DEFINED ROBORUN_ROBOT OR
   NOT DEFINED ROBORUN_POINTS OR NOT DEFINED ROBORUN_IO OR NOT DEFINED ROBORUN_TOOLS OR
   NOT DEFINED ROBORUN_SCENARIO)
  message(FATAL_ERROR "determinism check requires ROBORUN_BIN, ROBORUN_PROGRAM, ROBORUN_ROBOT, ROBORUN_POINTS, ROBORUN_IO, ROBORUN_TOOLS and ROBORUN_SCENARIO")
endif()

set(COMMON_ARGS run --backend mock --format trace
  --robot-config "${ROBORUN_ROBOT}"
  --points-config "${ROBORUN_POINTS}"
  --io-config "${ROBORUN_IO}"
  --tool-config "${ROBORUN_TOOLS}"
  --scenario "${ROBORUN_SCENARIO}"
  --program "${ROBORUN_PROGRAM}")

execute_process(COMMAND "${ROBORUN_BIN}" ${COMMON_ARGS}
  RESULT_VARIABLE FIRST_RESULT OUTPUT_VARIABLE FIRST_OUTPUT ERROR_VARIABLE FIRST_ERROR)
execute_process(COMMAND "${ROBORUN_BIN}" ${COMMON_ARGS}
  RESULT_VARIABLE SECOND_RESULT OUTPUT_VARIABLE SECOND_OUTPUT ERROR_VARIABLE SECOND_ERROR)
execute_process(COMMAND "${ROBORUN_BIN}" ${COMMON_ARGS}
  RESULT_VARIABLE THIRD_RESULT OUTPUT_VARIABLE THIRD_OUTPUT ERROR_VARIABLE THIRD_ERROR)

if(NOT FIRST_RESULT EQUAL 0 OR NOT SECOND_RESULT EQUAL 0 OR NOT THIRD_RESULT EQUAL 0)
  message(FATAL_ERROR "determinism run failed: first=${FIRST_RESULT} ${FIRST_ERROR}; second=${SECOND_RESULT} ${SECOND_ERROR}; third=${THIRD_RESULT} ${THIRD_ERROR}")
endif()
if(NOT FIRST_OUTPUT STREQUAL SECOND_OUTPUT OR NOT FIRST_OUTPUT STREQUAL THIRD_OUTPUT)
  message(FATAL_ERROR "trace output is not deterministic\nFIRST:\n${FIRST_OUTPUT}\nSECOND:\n${SECOND_OUTPUT}\nTHIRD:\n${THIRD_OUTPUT}")
endif()
